<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Site</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: white;
            padding: 10px 0;
            text-align: center;
        }
        .content {
            padding: 20px;
        }
    </style>
</head>
<body>

    <header>
        <h1>Bem-vindo ao Meu Site!</h1>
    </header>

    <div class="content">
        <p>Este é um site simples que será hospedado em HTTPS.</p>
    </div>

</body>
</html>
